<?xml version="1.0" encoding="utf-8"?>
<Database Name="STUDENTDATABASE" Class="StudentLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HKEDU01\SQLEXPRESS;Initial Catalog=STUDENTDATABASE;Integrated Security=True;Pooling=False" SettingsObjectName="StudentDbLinq.Properties.Settings" SettingsPropertyName="STUDENTDATABASEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Student">
    <Type Name="Student">
      <Column Name="Student_ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Student_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_chk" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Student_InDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>